### PR TITLE
General improvements and adjustments

### PR DESCRIPTION
**Pull request by Vlix**
I got carried away a little.

- I removed some unnecessary checks
  (e.g. `_nul <= w8` and `w8 <= _ydieresis` are always `True`)
- I adjusted `Data.Word8.isAscii` and benchmarks to make sure it is actually an improvement (it is, marginally)
- Adjusted documentation and added documentation
  (including helpful info for every byte constant in `Data.Word8`)

This probably needs a version bump, but should this be a patch or minor version bump? (i.e. `0.1.2.1` or `0.1.3`?)

### CODE REVIEW

**Comment by Vlix** [comment]
Oh, I just noticed `0.1.3` is already on hackage... is this repo not up to date?! :thinking:

**Comment by kazu-yamamoto** [comment]
Very strange.
My local `main` is exactly the same as that of github.
I should dig it deeper.

**Comment by kazu-yamamoto** [comment]
The diff of `main` and v0.1.3 is version number only.
I pushed a new commit to fix this inconsistency.

**Comment by Vlix** [comment]
Ok, so should this update be `0.1.4` or `0.1.3.1`?
I haven't touched the API, so either would qualify, I think.

**Comment by kazu-yamamoto** [comment]
Unlike `wai`, you don't have to modify version by yourself.

**Comment by kazu-yamamoto** [comment]
This is awesome!
Rebased and merged.
Thank you for your contribution!

**Pull request closed without merging**
